#!/usr/bin/env python3
"""Generate cfg_schema.h from SONiC YANG models — Bazel build-time codegen.

This is a pure-Python replacement for the upstream gen_cfg_schema.py that
needs sonic_yang + libyang at runtime. We don't pull in those wheels here;
instead we directly scan the yang text for the same pattern that
gen_cfg_schema.py's libyang-based loop discovers:

    module sonic-foo {
        ...
        container sonic-foo {           <-- top-level wrapper
            container <TABLE_NAME> {    <-- CONFIG_DB table
                ...
            }
            container <ANOTHER_TABLE> { ... }
        }
    }

Each such inner-container name becomes `#define CFG_<NAME>_TABLE_NAME "<NAME>"`.
Names with hyphens are emitted as comments (can't be valid C macros), exactly
matching upstream gen_cfg_schema.py's behaviour.

Usage:
    cfg_schema_gen.py --yang-dir <yang_models_dir> --out <cfg_schema.h>

The yang dir is whatever you point at — the script just globs *.yang under it.
"""

import argparse
import glob
import os
import re
import sys


HEADER = """#ifndef CFG_SCHEMA_H
#define CFG_SCHEMA_H

// Macros for table names are autogenerated by cfg_schema_gen.py. Manual update will not be preserved.
#ifdef __cplusplus
namespace swss {
#endif
"""

FOOTER = """
#ifdef __cplusplus
}
#endif
#endif"""


_MODULE_RE = re.compile(r'\bmodule\s+([\w-]+)\s*\{')
_TOP_RE = re.compile(r'\bcontainer\s+([\w-]+)\s*\{')
_CONTAINER_RE = re.compile(r'container\s+([\w-]+)\s*\{')
_LINE_COMMENT = re.compile(r'//[^\n]*')
_BLOCK_COMMENT = re.compile(r'/\*.*?\*/', re.S)


def _strip_comments(text: str) -> str:
    text = _BLOCK_COMMENT.sub('', text)
    text = _LINE_COMMENT.sub('', text)
    return text


def _find_matching_brace(text: str, start: int) -> int:
    """Given index of `{`, return index of matching `}`."""
    depth = 1
    i = start + 1
    while i < len(text):
        c = text[i]
        if c == '{':
            depth += 1
        elif c == '}':
            depth -= 1
            if depth == 0:
                return i
        i += 1
    return -1


def extract_keys(yang_text: str) -> set:
    """Return the set of CONFIG_DB table names found in a single yang module.

    Mirrors sonic_yang_ext._createDBTableToModuleMap exactly:
      - take the first top-level container under `module M { ... }`
      - if that container's name == M, treat its immediate child containers
        as CONFIG_DB tables; otherwise skip the module
    """
    text = _strip_comments(yang_text)
    keys = set()

    mod_match = _MODULE_RE.search(text)
    if not mod_match:
        return keys
    module_name = mod_match.group(1)
    # Walk into the module body
    mod_open = text.find('{', mod_match.end() - 1)
    if mod_open < 0:
        return keys
    mod_close = _find_matching_brace(text, mod_open)
    if mod_close < 0:
        return keys
    mod_body = text[mod_open + 1:mod_close]

    # Find the first top-level container inside the module body
    # (skip any other constructs — imports, revisions, typedefs, etc.)
    depth = 0
    i = 0
    top_name = None
    top_open = -1
    while i < len(mod_body):
        c = mod_body[i]
        if c == '{':
            depth += 1
            i += 1
            continue
        if c == '}':
            depth -= 1
            i += 1
            continue
        if depth == 0:
            mm = _TOP_RE.match(mod_body, i)
            if mm:
                top_name = mm.group(1)
                top_open = mm.end() - 1
                break
        i += 1

    # Only consider this module if its first top-level container matches
    # the module name (per SONiC YANG model guidelines).
    if top_name != module_name:
        return keys

    top_close = _find_matching_brace(mod_body, top_open)
    if top_close < 0:
        return keys
    body = mod_body[top_open + 1:top_close]

    # Walk body, only matching `container NAME {` at depth 0 (immediate child).
    depth = 0
    i = 0
    while i < len(body):
        c = body[i]
        if c == '{':
            depth += 1
            i += 1
            continue
        if c == '}':
            depth -= 1
            i += 1
            continue
        if depth == 0:
            mm = _CONTAINER_RE.match(body, i)
            if mm:
                keys.add(mm.group(1))
                inner_open = mm.end() - 1
                inner_close = _find_matching_brace(body, inner_open)
                if inner_close < 0:
                    break
                i = inner_close + 1
                continue
        i += 1
    return keys


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--yang-dir', required=True, help='Directory of *.yang files')
    parser.add_argument('--out', required=True, help='Output cfg_schema.h path')
    args = parser.parse_args()

    keys = set()
    yang_files = sorted(glob.glob(os.path.join(args.yang_dir, '*.yang')))
    if not yang_files:
        print('cfg_schema_gen: no *.yang files in {}'.format(args.yang_dir), file=sys.stderr)
        sys.exit(1)
    for path in yang_files:
        with open(path) as f:
            keys.update(extract_keys(f.read()))

    with open(args.out, 'w') as f:
        f.write(HEADER)
        f.write('\n')
        for key in sorted(keys):
            if '-' in key:
                f.write('// #define CFG_{}_TABLE_NAME "{}"\n'.format(key, key))
            else:
                f.write('#define CFG_{}_TABLE_NAME "{}"\n'.format(key, key))
        f.write(FOOTER)


if __name__ == '__main__':
    main()
